version: '3'

services:
  app:
    restart: unless-stopped
    container_name: vcx_app
    hostname: app
    restart: always
    build:
      context: .
    volumes:
      - ./data:/root/data
      - ./web:/root/web
      - ./server:/root/server
    ports:
      - "8080:80"
    env_file:
      - ./config/env.dev
    networks:
      - vcx_network
networks:
  vcx_network:
volumes:
  vcx_app_volume: